// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types'; // Path is correct if types.ts is in the same folder

const SUPABASE_URL = "https://vswctyplzrwjgnwxplhg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzd2N0eXBsenJ3amdud3hwbGhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2ODMyNTgsImV4cCI6MjA2NzI1OTI1OH0.eOPAUSyhLj8m9DPDcP1PASDqUP3PXWu9C5h8v1-07JM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
