-- Drop all existing RLS policies
DROP POLICY IF EXISTS "Public profiles are viewable by everyone." ON public.profiles;
DROP POLICY IF EXISTS "Users can update their own profile." ON public.profiles;
DROP POLICY IF EXISTS "Users can delete their own profile." ON public.profiles;
DROP POLICY IF EXISTS "Public rooms are viewable by everyone." ON public.rooms;
DROP POLICY IF EXISTS "Users can create rooms." ON public.rooms;
DROP POLICY IF EXISTS "Owners can update their rooms." ON public.rooms;
DROP POLICY IF EXISTS "Owners can delete their rooms." ON public.rooms;
DROP POLICY IF EXISTS "Members can view private rooms they belong to." ON public.rooms;
DROP POLICY IF EXISTS "Authenticated users can view room members if they can view the room" ON public.room_members;
DROP POLICY IF EXISTS "Room owners/admins can insert members" ON public.room_members;
DROP POLICY IF EXISTS "Room owners/admins can update members" ON public.room_members;
DROP POLICY IF EXISTS "Users can remove themselves from a room" ON public.room_members;
DROP POLICY IF EXISTS "Room owners/admins can remove any member" ON public.room_members;
DROP POLICY IF EXISTS "Room members can view messages in their room." ON public.messages;
DROP POLICY IF EXISTS "Room members can send messages." ON public.messages;
DROP POLICY IF EXISTS "Sender can update their own messages." ON public.messages;
DROP POLICY IF EXISTS "Sender can delete their own messages." ON public.messages;
DROP POLICY IF EXISTS "Users can send friend requests." ON public.friend_requests;
DROP POLICY IF EXISTS "Users can view their own sent and received friend requests." ON public.friend_requests;
DROP POLICY IF EXISTS "Users can update their own received friend requests (accept/reject/block)." ON public.friend_requests;
DROP POLICY IF EXISTS "Users can delete their own sent friend requests (cancel)." ON public.friend_requests;
DROP POLICY IF EXISTS "Badges are viewable by everyone." ON public.badges;
DROP POLICY IF EXISTS "Users can view their own awarded badges." ON public.user_badges;
DROP POLICY IF EXISTS "Allow function to insert user badges." ON public.user_badges;
DROP POLICY IF EXISTS "Users can view their own subscriptions." ON public.subscriptions;
DROP POLICY IF EXISTS "Users can update their own subscriptions (e.g., cancel)." ON public.subscriptions;
DROP POLICY IF EXISTS "Users can view their own notifications." ON public.notifications;
DROP POLICY IF EXISTS "Users can update their own notifications (e.g., mark as read)." ON public.notifications;
DROP POLICY IF EXISTS "All users can view badges" ON public.badges;
DROP POLICY IF EXISTS "Members can insert their own membership" ON public.conversation_members;
DROP POLICY IF EXISTS "Users can view their own membership" ON public.conversation_members;
DROP POLICY IF EXISTS "Users can view conversations they are a member of" ON public.conversations;
DROP POLICY IF EXISTS "Participants can delete friend requests" ON public.friends;
DROP POLICY IF EXISTS "Participants can update friend requests" ON public.friends;
DROP POLICY IF EXISTS "Users can read own friends" ON public.friends;
DROP POLICY IF EXISTS "Users can send friend requests" ON public.friends;
DROP POLICY IF EXISTS "Users can update their own messages" ON public.messages;
DROP POLICY IF EXISTS "Users can update their notifications" ON public.notifications;
DROP POLICY IF EXISTS "Users can view their notifications" ON public.notifications;
DROP POLICY IF EXISTS "Users can insert own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can read own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can view own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can view public profile data" ON public.profiles;
DROP POLICY IF EXISTS "Members can view room members (secure)" ON public.room_members;
DROP POLICY IF EXISTS "Room creators can manage members" ON public.room_members;
DROP POLICY IF EXISTS "Room creators can remove members" ON public.room_members;
DROP POLICY IF EXISTS "Users can join rooms" ON public.room_members;
DROP POLICY IF EXISTS "Users can leave rooms" ON public.room_members;
DROP POLICY IF EXISTS "Users can read room members" ON public.room_members;
DROP POLICY IF EXISTS "Users can view own memberships" ON public.room_members;
DROP POLICY IF EXISTS "Anyone can view public rooms" ON public.rooms;
DROP POLICY IF EXISTS "Creators can delete own rooms" ON public.rooms;
DROP POLICY IF EXISTS "Creators can update own rooms" ON public.rooms;
DROP POLICY IF EXISTS "Users can create rooms" ON public.rooms;
DROP POLICY IF EXISTS "Users can read accessible rooms" ON public.rooms;
DROP POLICY IF EXISTS "Users can update own rooms" ON public.rooms;
DROP POLICY IF EXISTS "Users can view their own subscriptions" ON public.subscriptions;
DROP POLICY IF EXISTS "Other users can view user badges" ON public.user_badges;
DROP POLICY IF EXISTS "Users can view their own badges" ON public.user_badges;
DROP POLICY IF EXISTS "Other users can view user streaks" ON public.user_streaks;
DROP POLICY IF EXISTS "Users can view their own streaks" ON public.user_streaks;
